### PR TITLE
Swagger for ProductOffer Controller

### PR DESCRIPTION
**Pull request by Swap203**
Swagger for ProductOffer Controller
Added @ApiModelProperty  for com.app.cart.entity.ProductOffer : For information about data of a model property.

### CODE REVIEW

**Comment by omini007** [comment]
Hard re

**Comment by Swap203** [comment]
ajun jaga hais vhay re...

**Comment by omini007** [comment]
Ho, zopto ata

**Comment by omini007** [comment]
Pull request karun thev ajun astil tar, saglyancha code zala ki merge karu.

**Pull request merged**
