### PR TITLE
Merge pull request #8 from prongzz/master

### PR DESCRIPTION
**Pull request by Swap203**
pulling from Master Origin

### CODE REVIEW

**Comment by prongzz** [comment]
Ase kartays bagh 😂😂😂

**Comment by omini007** [comment]
Blank PR send keli ka? :smile:

**Comment by Swap203** [comment]
are to compare cha option yeyina ki...

**Comment by omini007** [comment]
karaycha kay ahe nakki?

**Comment by prongzz** [comment]
Are kehna kya chahte ho ? 😂😂

**Pull request closed without merging**
